### ISSUE TITLE
Filter out Gateways before reconciliation

### ISSUE THREAD

**Issue by mlavacca** [Kong/blixt#17]
## Problem Statement

Every time a new `Gateway` gets reconciled by the Gateway controller, the controller must check the:
* `GatewayClass` referenced by the `Gateway` exists
* `GatewayClass.Spec.ControllerName` matches with Blixt's `controllerName` 

These two checks should be moved to a predicate to save reconciliation loops not needed for `Gateway`s not backed by Blixt's `GatewayClass`es.

## Acceptance Criteria
- [ ] the aforementioned checks are moved to a predicate that runs in the Gateway controller.
- [ ] a unit test for such a predicate must be added

**Comment by Rahul-D78** [comment]
Hi @mlavacca can i work on this one

**Comment by mlavacca** [comment]
Hi @Rahul-D78, of course. Feel free to assign yourself 👍

**Comment by mlavacca** [comment]
> /assign

We don't have this kind of automation yet :)

**Comment by Rahul-D78** [comment]
Can we use a constant value for `Blixt's controllerName` or it is predefined.
Can you please give some context regarding this -- `GatewayClass referenced by the Gateway exists`

**Comment by mlavacca** [comment]
> Can we use a constant value for `Blixt's controllerName` or it is predefined. Can you please give some context regarding this -- `GatewayClass referenced by the Gateway exists`

Basically the following portion of code should be put into a predicate:
https://github.com/Kong/blixt/blob/69655b46bd244cbcc48695ad8d3d06d823091e7a/controllers/gateway_controller.go#L63-L73

**Comment by shaneutt** [comment]
Relevant to https://github.com/Kong/blixt/pull/20#pullrequestreview-1177793685 I'm going to add an initial unit test here.
