### ISSUE TITLE
golangci-lint workflow runner timing out

### ISSUE THREAD

**Issue by shaneutt** [Kong/blixt#27]
I've noticed every once in a while the golangci-lint runner times out and fails, but works when you retry. We're using all the default settings and the latest release so I'm not sure why this would be failing. It's possible that just setting an explicit timeout longer than the default would help, but it really seems like the default timeout should be enough. It's possible this is a problem upstream. If someone is looking for some lower hanging fruit and can spare some cycles on this it would be appreciated, thus marking it as good first issue / help wanted.

**Comment by acald-creator** [comment]
@shaneutt 

I would like to help with this.

As I've noticed from your previous workflow runs, lint workflow would time out after 1 minute. `golangci-lint` uses the default timeout at 1 minute. Perhaps increasing it overtime will help?

I can still continue to do research to find what is the best recommendation in terms of specifying the timeouts versus the size of the project.

I can submit a PR momentarily with the timeout setup.

**Comment by acald-creator** [comment]
@shaneutt 

Thanks for your response. I completely understand.

I've been testing `golangci-lint` in other Go projects, I've noticed that sometimes it will run pretty quick, which via CI or locally, or pretty slow. As far as I know `golangci-lint` GitHub Action is supposed to be using `cache` internally.

But I agree, we will have to tweak it in the future.

Do you have a community channel to collaborate on this project? I would like to become involved in the long run as well.

**Comment by shaneutt** [comment]
@acald-creator sounds good, I too was expecting their action to handle cache but just to make sure we don't lose an opportunity to check if things are working correctly, I created https://github.com/Kong/blixt/issues/29 for later.

> Do you have a community channel to collaborate on this project? I would like to become involved in the long run as well.

Awesome! And yes we do, but it's in a bit of a limbo at the moment: we (Kong) are currently submitting the project for donation to Kubernetes SIG Network for use in Gateway API testing (for context, I am one of the Gateway API maintainers). As such it doesn't have a clear permanent home just yet. For now the [discussions board](https://github.com/Kong/blixt/discussions) is a great place for async conversations, or for slightly more synchronous conversations the `#sig-network-gateway-api` channel on [Kubernetes Slack](https://kubernetes.slack.com) is a good place as well. If you'd like to track the current conversation in SIG Network about donating it to https://github.com/kubernetes-sigs, see https://groups.google.com/g/kubernetes-sig-network/c/z_N1cLTUO8M.
