### ISSUE TITLE
Make container image names consistent

### ISSUE THREAD

**Issue by shaneutt** [Kong/blixt#32]
## Problem Statement

We publish two images at the moment:

- `blixt-control-plane`
- `blixt-dataplane`

It's really minor, but we might as well make these consistent so let's update the former to `blixt-controlplane` or the later to `blixt-data-plane`, one or the other :shrug:

**Comment by RudranshGoel** [comment]
I cannot really locate the files. Could you guide me to them?

**Comment by shaneutt** [comment]
> I cannot really locate the files. Could you guide me to them?

Sure :+1:

It's a couple of small changes:

- https://github.com/Kong/blixt/blob/main/Makefile#L50
- https://github.com/Kong/blixt/blob/main/.github/workflows/ci.yaml#L85

Also you'll need a maintainer to add the ghrc repository, I'll get started on that.

**Comment by shaneutt** [comment]
https://github.com/Kong/blixt/pkgs/container/blixt-controlplane is now created, so should be ready to use :+1:
