### ISSUE TITLE
Support Gateway API v0.7.x

### ISSUE THREAD

**Issue by shaneutt** [Kong/blixt#56]
### Problem Statement

Up until now we had been developing and testing entirely against [Gateway API v0.5.1](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.5.1). Now that [v0.7.1 has released](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.7.1) which includes some backwards incompatible changes, we should update to support it. There's not a lot to do at this point as we're still early in development and haven't yet deeply implemented statuses, but we should at least make sure we're covering the new `Programmed` and `Ready` status setup.

### Acceptance Criteria

- [x] all test suites deploy using `v0.7.x`
- [x] `Gateway` resources have their `Programmed` status appropriately set
- [ ] the `README.md` (and any other relevant documentation) refers to using `v0.7.x`

**Comment by synthe102** [comment]
Hey! I'd like to help on this one if possible.

**Comment by shaneutt** [comment]
Sounds great, thank you! Let us know here or in `#sig-network-gateway-api` on K8s slack if you need any help!

**Comment by shaneutt** [comment]
@synthe102 just wanted to give you a heads up I was blocked on a newer Gateway API to resolve #12 so without remembering that you were on this one, I ended up resolving it as a side effect of #92 (though at this point, we jumped straight to v0.7.1, we passed right over v0.6.x). Sorry about any confusion I had completely forgot about this issue.
