### ISSUE TITLE
Cleanup ip address print helper in the dataplane

### ISSUE THREAD

**Issue by astoycos** [Kong/blixt#71]
Currently to print a human readable ip address in the dataplane we do something like the following 

```
    let daddr_dot_dec = ip_from_int(unsafe { (*ip_hdr).daddr });
    info!(
        &ctx,
        "Received a ICMP Unreachable packet destined for svc ip: {}.{}.{}.{}",
        daddr_dot_dec[0],
        daddr_dot_dec[1],
        daddr_dot_dec[2],
        daddr_dot_dec[3],
    );
```

Let's add a wrapper function on top of this to clean things up even more.

**Comment by rushi47** [comment]
@shaneutt @astoycos can I work on this, as I see its small PR I can test my rust skills to see it in action

**Comment by shaneutt** [comment]
Sounds great @rushi47! Check in with us in here, or in Kubernetes slack if you run into problems!

**Comment by rushi47** [comment]
thanks @shaneutt :)
